spring:
  application:
    name: enrollment-system

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        default_batch_fetch_size: 100
        jdbc:
          time_zone: Asia/Seoul

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    root: info
    org.hibernate.SQL: debug
