INSERT INTO creator (creator_id, name, email, status)
VALUES
    (1, '강사1', 'creator1@liveclass.com', 'ACTIVE'),
    (2, '강사2', 'creator2@liveclass.com', 'ACTIVE'),
    (3, '강사3', 'creator3@liveclass.com', 'ACTIVE'),
    (4, '강사4', 'creator4@liveclass.com', 'ACTIVE'),
    (5, '강사5', 'creator5@liveclass.com', 'ACTIVE'),
    (6, '강사6', 'creator6@liveclass.com', 'ACTIVE'),
    (7, '강사7', 'creator7@liveclass.com', 'ACTIVE'),
    (8, '강사8', 'creator8@liveclass.com', 'ACTIVE'),
    (9, '강사9', 'creator9@liveclass.com', 'ACTIVE'),
    (10, '강사10', 'creator10@liveclass.com', 'ACTIVE');

INSERT INTO classmate (classmate_id, name, email, status)
VALUES
    (1, '수강생1', 'classmate1@liveclass.com', 'ACTIVE'),
    (2, '수강생2', 'classmate2@liveclass.com', 'ACTIVE'),
    (3, '수강생3', 'classmate3@liveclass.com', 'ACTIVE'),
    (4, '수강생4', 'classmate4@liveclass.com', 'ACTIVE'),
    (5, '수강생5', 'classmate5@liveclass.com', 'ACTIVE'),
    (6, '수강생6', 'classmate6@liveclass.com', 'ACTIVE'),
    (7, '수강생7', 'classmate7@liveclass.com', 'ACTIVE'),
    (8, '수강생8', 'classmate8@liveclass.com', 'ACTIVE'),
    (9, '수강생9', 'classmate9@liveclass.com', 'ACTIVE'),
    (10, '수강생10', 'classmate10@liveclass.com', 'ACTIVE'),
    (11, '수강생11', 'classmate11@liveclass.com', 'ACTIVE'),
    (12, '수강생12', 'classmate12@liveclass.com', 'ACTIVE'),
    (13, '수강생13', 'classmate13@liveclass.com', 'ACTIVE'),
    (14, '수강생14', 'classmate14@liveclass.com', 'ACTIVE'),
    (15, '수강생15', 'classmate15@liveclass.com', 'ACTIVE'),
    (16, '수강생16', 'classmate16@liveclass.com', 'ACTIVE'),
    (17, '수강생17', 'classmate17@liveclass.com', 'ACTIVE'),
    (18, '수강생18', 'classmate18@liveclass.com', 'ACTIVE'),
    (19, '수강생19', 'classmate19@liveclass.com', 'ACTIVE'),
    (20, '수강생20', 'classmate20@liveclass.com', 'ACTIVE'),
    (21, '수강생21', 'classmate21@liveclass.com', 'ACTIVE'),
    (22, '수강생22', 'classmate22@liveclass.com', 'ACTIVE'),
    (23, '수강생23', 'classmate23@liveclass.com', 'ACTIVE'),
    (24, '수강생24', 'classmate24@liveclass.com', 'ACTIVE'),
    (25, '수강생25', 'classmate25@liveclass.com', 'ACTIVE'),
    (26, '수강생26', 'classmate26@liveclass.com', 'ACTIVE'),
    (27, '수강생27', 'classmate27@liveclass.com', 'ACTIVE'),
    (28, '수강생28', 'classmate28@liveclass.com', 'ACTIVE'),
    (29, '수강생29', 'classmate29@liveclass.com', 'ACTIVE'),
    (30, '수강생30', 'classmate30@liveclass.com', 'ACTIVE');