INSERT INTO creator (creator_id, name, email, status)
VALUES
    (1, 'creator_1', 'creator1@liveclass.com', 'ACTIVE'),
    (2, 'creator_2', 'creator2@liveclass.com', 'ACTIVE'),
    (3, 'creator_3', 'creator3@liveclass.com', 'ACTIVE'),
    (4, 'creator_4', 'creator4@liveclass.com', 'ACTIVE'),
    (5, 'creator_5', 'creator5@liveclass.com', 'ACTIVE'),
    (6, 'creator_6', 'creator6@liveclass.com', 'ACTIVE'),
    (7, 'creator_7', 'creator7@liveclass.com', 'ACTIVE'),
    (8, 'creator_8', 'creator8@liveclass.com', 'ACTIVE'),
    (9, 'creator_9', 'creator9@liveclass.com', 'ACTIVE'),
    (10, 'creator_10', 'creator10@liveclass.com', 'ACTIVE');

INSERT INTO classmate (classmate_id, name, email, status)
VALUES
    (1, 'classmate_1', 'classmate1@liveclass.com', 'ACTIVE'),
    (2, 'classmate_2', 'classmate2@liveclass.com', 'ACTIVE'),
    (3, 'classmate_3', 'classmate3@liveclass.com', 'ACTIVE'),
    (4, 'classmate_4', 'classmate4@liveclass.com', 'ACTIVE'),
    (5, 'classmate_5', 'classmate5@liveclass.com', 'ACTIVE'),
    (6, 'classmate_6', 'classmate6@liveclass.com', 'ACTIVE'),
    (7, 'classmate_7', 'classmate7@liveclass.com', 'ACTIVE'),
    (8, 'classmate_8', 'classmate8@liveclass.com', 'ACTIVE'),
    (9, 'classmate_9', 'classmate9@liveclass.com', 'ACTIVE'),
    (10, 'classmate_10', 'classmate10@liveclass.com', 'ACTIVE'),
    (11, 'classmate_11', 'classmate11@liveclass.com', 'ACTIVE'),
    (12, 'classmate_12', 'classmate12@liveclass.com', 'ACTIVE'),
    (13, 'classmate_13', 'classmate13@liveclass.com', 'ACTIVE'),
    (14, 'classmate_14', 'classmate14@liveclass.com', 'ACTIVE'),
    (15, 'classmate_15', 'classmate15@liveclass.com', 'ACTIVE'),
    (16, 'classmate_16', 'classmate16@liveclass.com', 'ACTIVE'),
    (17, 'classmate_17', 'classmate17@liveclass.com', 'ACTIVE'),
    (18, 'classmate_18', 'classmate18@liveclass.com', 'ACTIVE'),
    (19, 'classmate_19', 'classmate19@liveclass.com', 'ACTIVE'),
    (20, 'classmate_20', 'classmate20@liveclass.com', 'ACTIVE'),
    (21, 'classmate_21', 'classmate21@liveclass.com', 'ACTIVE'),
    (22, 'classmate_22', 'classmate22@liveclass.com', 'ACTIVE'),
    (23, 'classmate_23', 'classmate23@liveclass.com', 'ACTIVE'),
    (24, 'classmate_24', 'classmate24@liveclass.com', 'ACTIVE'),
    (25, 'classmate_25', 'classmate25@liveclass.com', 'ACTIVE'),
    (26, 'classmate_26', 'classmate26@liveclass.com', 'ACTIVE'),
    (27, 'classmate_27', 'classmate27@liveclass.com', 'ACTIVE'),
    (28, 'classmate_28', 'classmate28@liveclass.com', 'ACTIVE'),
    (29, 'classmate_29', 'classmate29@liveclass.com', 'ACTIVE'),
    (30, 'classmate_30', 'classmate30@liveclass.com', 'ACTIVE');